name: Build Battery Modules

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - 'v*'
    paths:
      - 'extra_modules/**'
      - '.github/workflows/build-modules.yml'
      - '.github/workflows/ddk-build-modules.yml'

jobs:
  build:
    strategy:
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
    uses: ./.github/workflows/ddk-build-modules.yml
    with:
      kmi: ${{ matrix.kmi }}
      ddk_release: '20251104'

  release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Debug Info
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: modules-*      # 匹配你的 artifact 名称
          merge-multiple: true

      - name: Repackage
        run: |
          mkdir release_files
          find artifacts -name "*.ko" -exec cp {} release_files/ \;
          ls -la release_files/
          [ "$(ls -A release_files)" ] || { echo "No .ko files!"; exit 1; }

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_files/*
          generate_release_notes: true
          fail_on_unmatched_files: true
